#!/bin/bash

# install build tools
pip install build
pip install twine
pip install hatch


# increment version in pyproject.toml
hatch version micro
git add git_time_tracking/__about__.py
git commit -m "bump version"
git push

# build package
python3 -m build --wheel

# upload to pypi
python3 -m twine upload dist/*
python3 -m twine upload --skip-existing --repository gitea dist/*