#!/bin/bash

# install build tools
pip install build

# build package
python3 -m build

# upload to pypi
python3 -m twine upload dist/*
python3 -m twine upload --skip-existing --repository gitea dist/*